

zone "cloud.local" IN { type master; file "/etc/bind/db.cloud.local"; };

http local {
        endpoints { "/dns-query"; };
};

options {
        directory "/var/cache/bind";
	allow-query { any; }; recursion yes;
	listen-on { any; };
        listen-on-v6 { any; };
        listen-on tls ephemeral { any; };
        listen-on-v6 tls ephemeral { any; };
        listen-on tls ephemeral http local { any; };
        listen-on-v6 tls ephemeral http local { any; };
};
